Repository replicatedhq/kurlkinds, pull requests merged in 2022-10, with the labels that each got.

#4 feat: add flannel add-on and minio management flag
  config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  pkg/apis/cluster/v1beta1/deepcopy_generated.go
  pkg/apis/cluster/v1beta1/installer_types.go
  schemas/installer-cluster-v1beta1.json
  schemas/installer-kurl-v1beta1.json
Labels: type::feature

#6 chore: error out on wrong installers api return
  pkg/lint/lint_test.go
  pkg/lint/rego/output.rego
Labels: type::chore

#7 Flannel and Rook and EKCO compatibility lint rules
  Makefile
  pkg/lint/rego/functions.rego
  pkg/lint/rego/output.rego
  pkg/lint/tests/rego/flannel_incomplete_cidr_range.yaml
  pkg/lint/tests/rego/invalid_flannel_pod_cidr_range.yaml
  pkg/lint/tests/rego/invalid_flannel_version.yaml
  pkg/lint/tests/rego/kubernetes_without_cni.yaml
  pkg/lint/tests/rego/multiple_cnis.yaml
  pkg/lint/tests/rego/multiple_kubernetes_distribution_selected.yaml
  pkg/lint/tests/rego/no_cni_no_container_runtime.yaml
  pkg/lint/tests/rego/rook_1.8_ekco_gt_0.22.0.yaml
  pkg/lint/tests/rego/rook_1.8_ekco_gt_0.22.0_valid.yaml
  pkg/lint/tests/rego/rook_1.9_ekco_gt_0.23.0.yaml
  pkg/lint/tests/rego/rook_1.9_ekco_gt_0.23.0_valid.yaml
  pkg/lint/tests/versions.json
Labels: type::chore

#9 bug: considering empty version as not selected add-on
  pkg/lint/lint.go
  pkg/lint/lint_test.go
  pkg/lint/options.go
  pkg/lint/rego/functions.rego
  pkg/lint/rego/output.rego
  pkg/lint/tests/rego/empty_versions.yaml
  pkg/lint/tests/unmarshal/empty_versions.yaml
Labels: bug::normal, type::bug
