Repository replicatedhq/kurlkinds, pull requests merged in 2022-11, with the labels that each got.

#10 bug: fix multi-x in add-on version
  pkg/lint/rego/functions.rego
  pkg/lint/tests/rego/invalid_addon_xxx_version.yaml
Labels: bug::normal, type::bug

#11 Remove support for k3s and rke2 add-ons
  config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  pkg/apis/cluster/v1beta1/installer_types.go
  pkg/lint/rego/functions.rego
  pkg/lint/rego/output.rego
  pkg/lint/tests/rego/empty_versions.yaml
  pkg/lint/tests/rego/invalid_k3s_version.yaml
  pkg/lint/tests/rego/invalid_minio_version.yaml
  pkg/lint/tests/rego/invalid_openebs_version.yaml
  pkg/lint/tests/rego/invalid_registry_version.yaml
  pkg/lint/tests/rego/invalid_rke2_version.yaml
  pkg/lint/tests/rego/invalid_rook_version.yaml
  pkg/lint/tests/rego/invalid_velero_version.yaml
  pkg/lint/tests/rego/k3s_incompatible_add_ons.yaml
  pkg/lint/tests/rego/k3s_with_container_runtime.yaml
  pkg/lint/tests/rego/k3s_without_container_runtime.yaml
  pkg/lint/tests/rego/kotsadm_invalid_ui_bind_port_k3s.yaml
  pkg/lint/tests/rego/kotsadm_invalid_ui_bind_port_rke2.yaml
  pkg/lint/tests/rego/multiple_kubernetes_distribution_selected.yaml
  pkg/lint/tests/rego/no_kubernetes_distribution_selected.yaml
  pkg/lint/tests/rego/rke2_incompatible_add_ons.yaml
  pkg/lint/tests/rego/rke2_with_container_runtime.yaml
  pkg/lint/tests/rego/rke2_without_container_runtime.yaml
  pkg/lint/tests/unmarshal/empty_versions.yaml
  pkg/lint/tests/versions.json
  schemas/installer-cluster-v1beta1.json
  schemas/installer-kurl-v1beta1.json
Labels: type::feature

#16 chore: using rego net.cidr_is_valid
  pkg/lint/rego/functions.rego
Labels: type::chore

#17 chore: adding debug capabilities to linter
  pkg/lint/lint.go
  pkg/lint/options.go
  pkg/lint/rego/debug.rego
Labels: type::chore
