Repository replicatedhq/kurlkinds, pull requests merged in 2023-04, with the labels that each got.

#90 bug: linter should not return info severity by default
  pkg/lint/rego/output.rego
  pkg/lint/tests/infosev/invalid_containerd_version.yaml
  pkg/lint/tests/infosev/invalid_docker_version.yaml
  pkg/lint/tests/rego/invalid_containerd_version.yaml
  pkg/lint/tests/rego/invalid_docker_version.yaml
  pkg/lint/tests/rego/invalid_flannel_docker.yaml
  pkg/lint/tests/rego/kubernetes_gte_1.24_plus_docker_container_runtime.yaml
  pkg/lint/tests/rego/kubernetes_gte_1.26_plus_containerd_lt_1.6.yaml
  pkg/lint/tests/rego/kubernetes_with_multiple_container_runtimes.yaml
  pkg/lint/tests/rego/multiple_invalid_versions.yaml
  pkg/lint/tests/rego/no_kubernetes_distribution_selected.yaml
  pkg/lint/tests/unmarshal/installer_invalid_versions.yaml
Labels: bug::normal, type::bug

#91 prompt to add latest ekco
  pkg/lint/rego/output.rego
  pkg/lint/tests/infosev/invalid_containerd_version.yaml
  pkg/lint/tests/infosev/invalid_docker_version.yaml
  pkg/lint/tests/infosev/k8s_1.26_rook_1.8_ekco_0.22.yaml
Labels: type::feature

#97 no matter the ekco version, only show an info message
  pkg/lint/rego/output.rego
  pkg/lint/tests/infosev/invalid_ekco_version.yaml
  pkg/lint/tests/rego/invalid_ekco_version.yaml
  pkg/lint/tests/rego/multiple_invalid_versions.yaml
  pkg/lint/tests/unmarshal/installer_invalid_versions.yaml
Labels: bug::regression, type::bug

#98 fix: ekco fail for invalid versions < 2023.04.06-1
  pkg/lint/rego/output.rego
  pkg/lint/tests/infosev/invalid_ekco_version_v2023.04.11-0.yaml
  pkg/lint/tests/rego/invalid_ekco_version_v2023.04.05-0.yaml
Labels: bug::normal, type::bug

#96 chore(deps): bump github.com/replicatedhq/troubleshoot from 0.59.0 to 0.61.0
  config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  go.mod
  go.sum
  schemas/installer-cluster-v1beta1.json
  schemas/installer-kurl-v1beta1.json
Labels: type::chore

#95 add rook minimum node count param
  config/crds/v1beta1/cluster.kurl.sh_installers.yaml
  pkg/apis/cluster/v1beta1/installer_types.go
  schemas/installer-cluster-v1beta1.json
  schemas/installer-kurl-v1beta1.json
Labels: type::feature

#103 upgrade k8s 1.27 and go version to 1.20
  .github/workflows/test.yml
  client/kurlclientset/doc.go
  client/kurlclientset/typed/cluster/v1beta1/fake/fake_installer.go
  go.mod
  go.sum
Labels: type::chore
